# Generated by Django 2.1.7 on 2019-03-05 10:23

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20190305_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='biography',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
