# Generated by Django 2.1.7 on 2019-03-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False,

    dependencies = [
        ('projects', '0004_auto_20190304_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='origin',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
