# Generated by Django 2.1.7 on 2019-03-05 16:44

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('projects', '0005_auto_20190305_1604'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectIngredient',
            new_name='ProjectElement',
        ),
        migrations.AlterModelOptions(
            name='projectelement',
            options={'verbose_name_plural': 'Project elements'},
        ),
        migrations.RenameField(
            model_name='projectpage',
            old_name='ingredients',
            new_name='elements',
        ),
    ]
